{
 "title": "Computer Vision - Cats & Dogs (Workshop)",
 "tags": [
  "mlops",
  "computer-vision",
  "workshop"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Distribution des Prédictions (Cats vs Dogs)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cv_prediction_distribution_total{result=\"cat\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cv_prediction_distribution_total{result=\"dog\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📊 Dernières Prédictions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT created_at, prediction_result, ROUND(proba_cat::numeric, 2) as proba_cat, ROUND(proba_dog::numeric, 2) as proba_dog FROM predictions_feedback ORDER BY created_at DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Feedback_users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cv_user_feedback_total) by (feedback_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low Confidence Ratio (last 5m)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(cv_low_confidence_predictions_total[5m])) / sum(increase(cv_predictions_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps d'inférence",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cv_inference_time_seconds_sum{instance=\"cv_app:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🗄️ Statut Base de Données",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cv_database_connected" }
   ]
  }
 ]
}